language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  postgresql: "9.3"

before_script:
  - composer self-update
  # --prefer-source is required to avoid hitting GitHub API limit:
  # https://github.com/composer/composer/issues/1314
  - composer install --no-interaction --prefer-source --dev
  - psql -c 'create database flex-cms;' -U postgres
  - php artisan migrate --force
  - php artisan db:seed --force

script:
  - php artisan env
  - phpunit --verbose
