language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  # --prefer-source is required to avoid hitting GitHub API limit:
  # https://github.com/composer/composer/issues/1314
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --verbose
